### ISSUE TITLE
Kontakt > Adresse > Schließende Klammer ist Teil des Links

### ISSUE THREAD

**Issue by fiveop** [steffen-heublein/kinderbude-test#1]
Das sollte sie nicht sein. (Und ich würde ein Link zu OSM statt GM bevorzugen.)

**Comment by steffen-heublein** [comment]
OpenStreetMaps wäre mir auch sehr recht, aber ich habe da keine Erfahrung.

Das hier sollte ok, sein, oder? https://www.openstreetmap.org/way/61420712
